"""Application configuration — public facade (tuning in submodules; secrets in .env).

Edit tuning in src/config/*.py; API keys in .env (see .env.example).
Feature vector schema: src/ml/feature_schema.py.
"""

from src.collection.inventory import (
    CTI_DOWNLOAD_ALLOWLIST,
    GITHUB_BENIGN_REPOS,
    SYSINTERNALS_BASE_URLS,
)
from . import core, ml_settings, paths, providers, secrets
from src.ml import thresholds
from src.ml.feature_schema import EXEC_API_NAMES, FEATURE_NAMES
from src.ml.thresholds import (
    TARGET_FPR,
    TARGET_FPR_BENIGN_TIER_BOOTSTRAP,
    TARGET_FPR_BENIGN_TIER_PRODUCTION,
    TARGET_FPR_BOOTSTRAP,
    TARGET_FPR_GROWTH,
    get_dynamic_target_fpr,
)

# --- Paths and storage (re-exported from paths.py) ---

PROJECT_ROOT = paths.PROJECT_ROOT
SANDBOX_DIR = paths.SANDBOX_DIR
DB_PATH = paths.DB_PATH
BENIGN_DIR = paths.BENIGN_DIR
MODEL_PATH = paths.MODEL_PATH
ADWIN_PATH = paths.ADWIN_PATH
EVAL_LOG_PATH = paths.EVAL_LOG_PATH
EVAL_STATE_PATH = paths.EVAL_STATE_PATH
DRIFT_LOG_PATH = paths.DRIFT_LOG_PATH
MODEL_UPDATE_LOG_PATH = paths.MODEL_UPDATE_LOG_PATH
TRAINING_HISTORY_PATH = paths.TRAINING_HISTORY_PATH
LOG_PATH = paths.LOG_PATH
FIGURES_DIR = paths.FIGURES_DIR
REPOS_DIR = paths.REPOS_DIR


def ensure_dirs() -> None:
    """Create required directories (uses facade paths so monkeypatch works)."""
    for path in (
        SANDBOX_DIR,
        DB_PATH.parent,
        MODEL_PATH.parent,
        BENIGN_DIR,
        FIGURES_DIR,
        EVAL_STATE_PATH.parent,
        DRIFT_LOG_PATH.parent,
        MODEL_UPDATE_LOG_PATH.parent,
        TRAINING_HISTORY_PATH.parent,
        LOG_PATH.parent,
        REPOS_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)

# --- Secrets and env mirrors (.env; see secrets.py) ---

OTX_API_KEY = secrets.OTX_API_KEY
OLLAMA_BASE_URL = secrets.OLLAMA_BASE_URL
OLLAMA_MODEL = secrets.OLLAMA_MODEL
get_auth_key = secrets.get_auth_key
get_github_token = secrets.get_github_token
get_malshare_api_key = secrets.get_malshare_api_key
get_secrets = secrets.get_secrets
allow_local_benign = secrets.allow_local_benign
malshare_enabled = secrets.malshare_enabled
otx_enabled = secrets.otx_enabled
mb_fallback_malshare = secrets.mb_fallback_malshare
pe_source_discovery_enabled = secrets.pe_source_discovery_enabled
ollama_source_selection_enabled = secrets.ollama_source_selection_enabled
ollama_drift_context_report_enabled = secrets.ollama_drift_context_report_enabled

# --- Scheduler, logging, flags, collection (re-exported from core.py) ---

SCHED_ENABLED = core.SCHED_ENABLED
SCHED_INTERVAL_SECONDS = core.SCHED_INTERVAL_SECONDS
SCHED_MAX_RUNS = core.SCHED_MAX_RUNS
SCHED_RUN_ON_START = core.SCHED_RUN_ON_START
SCHED_JITTER_SECONDS = core.SCHED_JITTER_SECONDS
SCHED_ERROR_BACKOFF_SECONDS = core.SCHED_ERROR_BACKOFF_SECONDS
SCHED_MAX_BACKOFF_SECONDS = core.SCHED_MAX_BACKOFF_SECONDS
BOOTSTRAP_MAX_RUNS = core.BOOTSTRAP_MAX_RUNS
BOOTSTRAP_INTERVAL_SECONDS = core.BOOTSTRAP_INTERVAL_SECONDS
VERBOSE = core.VERBOSE
LOG_MAX_BYTES = core.LOG_MAX_BYTES
LOG_BACKUP_COUNT = core.LOG_BACKUP_COUNT
OLLAMA_LOG_DETAIL = core.OLLAMA_LOG_DETAIL
OLLAMA_LOG_MAX_CHARS = core.OLLAMA_LOG_MAX_CHARS
OLLAMA_LOG_CONSOLE_PREVIEW = core.OLLAMA_LOG_CONSOLE_PREVIEW
ALLOW_LOCAL_BENIGN = core.ALLOW_LOCAL_BENIGN
MALSHARE_ENABLED = core.MALSHARE_ENABLED
MB_FALLBACK_MALSHARE = core.MB_FALLBACK_MALSHARE
PE_SOURCE_DISCOVERY_ENABLED = core.PE_SOURCE_DISCOVERY_ENABLED
CTI_SEED_SOURCES_ENABLED = core.CTI_SEED_SOURCES_ENABLED
OLLAMA_ENABLED = core.OLLAMA_ENABLED
OLLAMA_SOURCE_SELECTION_ENABLED = core.OLLAMA_SOURCE_SELECTION_ENABLED
OLLAMA_DRIFT_CONTEXT_REPORT_ENABLED = core.OLLAMA_DRIFT_CONTEXT_REPORT_ENABLED
FORCED_BENIGN_PROVIDER = core.FORCED_BENIGN_PROVIDER
SEMANTIC_MIN_CONFIDENCE = core.SEMANTIC_MIN_CONFIDENCE
SEMANTIC_REQUIRE_TECHNICAL_REPORT = core.SEMANTIC_REQUIRE_TECHNICAL_REPORT
TARGET_MALWARE_BENIGN_RATIO = core.TARGET_MALWARE_BENIGN_RATIO
BENIGN_PROVIDER_NAMES = core.BENIGN_PROVIDER_NAMES
IMBALANCE_ALERT_RATIO = core.IMBALANCE_ALERT_RATIO
MALWARE_FALLBACK_PROVIDERS = core.MALWARE_FALLBACK_PROVIDERS
FALLBACK_PE_CHECK_MULT = core.FALLBACK_PE_CHECK_MULT
PE_DOWNLOAD_MAX_BYTES = core.PE_DOWNLOAD_MAX_BYTES
BENIGN_NET_REPO_URL = core.BENIGN_NET_REPO_URL
PE_DISCOVERY_MAX_URLS = core.PE_DISCOVERY_MAX_URLS
MIN_PE_SOURCES = core.MIN_PE_SOURCES
INTEL_MIN_POLL_INTERVAL = core.INTEL_MIN_POLL_INTERVAL
INTEL_MAX_POLL_INTERVAL = core.INTEL_MAX_POLL_INTERVAL
PROVIDER_COOLDOWN_ZERO_RUNS = core.PROVIDER_COOLDOWN_ZERO_RUNS
PROVIDER_COOLDOWN_SECONDS = core.PROVIDER_COOLDOWN_SECONDS
PROVIDER_COOLDOWN_MIN_ATTEMPTS = core.PROVIDER_COOLDOWN_MIN_ATTEMPTS
STEADY_BENIGN_EVERY_N = core.STEADY_BENIGN_EVERY_N
REPORT_LANGUAGE = core.REPORT_LANGUAGE

# --- ML training, drift, MADAR, evaluation (re-exported from ml_settings.py) ---

REPLAY_BUDGET = ml_settings.REPLAY_BUDGET
MIN_TRAIN_MALWARE = ml_settings.MIN_TRAIN_MALWARE
MIN_TRAIN_BENIGN = ml_settings.MIN_TRAIN_BENIGN
PE_FETCH_LIMIT = ml_settings.PE_FETCH_LIMIT
THRESHOLD_RETRAIN_MIN_NEW_SAMPLES = ml_settings.THRESHOLD_RETRAIN_MIN_NEW_SAMPLES
FEATURE_SELECTION_K = ml_settings.FEATURE_SELECTION_K
OPTUNA_TRIALS = ml_settings.OPTUNA_TRIALS
OPTUNA_TIMEOUT = ml_settings.OPTUNA_TIMEOUT
REPLAY_FRACTION = ml_settings.REPLAY_FRACTION
ADWIN_DELTA = ml_settings.ADWIN_DELTA
DRIFT_WINDOW_DAYS = ml_settings.DRIFT_WINDOW_DAYS
DRIFT_MIN_WINDOW_SAMPLES = ml_settings.DRIFT_MIN_WINDOW_SAMPLES
DRIFT_MEAN_SHIFT_THRESHOLD = ml_settings.DRIFT_MEAN_SHIFT_THRESHOLD
DRIFT_CORR_SHIFT_THRESHOLD = ml_settings.DRIFT_CORR_SHIFT_THRESHOLD
MADAR_CONTAMINATION = ml_settings.MADAR_CONTAMINATION
MADAR_ANOMALOUS_RATIO = ml_settings.MADAR_ANOMALOUS_RATIO
MADAR_CLASS_RATIO = ml_settings.MADAR_CLASS_RATIO
MADAR_BUDGET_STRATEGY = ml_settings.MADAR_BUDGET_STRATEGY
CONTINUATION_TREES = ml_settings.CONTINUATION_TREES
MAX_TOTAL_TREES = ml_settings.MAX_TOTAL_TREES
MODEL_ARCHIVE_DEPTH = ml_settings.MODEL_ARCHIVE_DEPTH
FEATURE_SET_VERSION = ml_settings.FEATURE_SET_VERSION
FEATURE_DIM = ml_settings.FEATURE_DIM
EVAL_EVERY_RUNS = ml_settings.EVAL_EVERY_RUNS
EVAL_SKIP_BOOTSTRAP = ml_settings.EVAL_SKIP_BOOTSTRAP
TESSERACT_MIXED_UNTIL_HEALTHY = ml_settings.TESSERACT_MIXED_UNTIL_HEALTHY
MIN_BENIGN_FOR_FPR = ml_settings.MIN_BENIGN_FOR_FPR

# --- FPR targets (re-exported from ml/thresholds.py) ---
# TARGET_FPR*, get_dynamic_target_fpr imported at module top

# --- External APIs (re-exported from providers.py) ---

API_URL = providers.API_URL
ZIP_PASSWORD = providers.ZIP_PASSWORD
MB_CIRCUIT_FAILURE_THRESHOLD = providers.MB_CIRCUIT_FAILURE_THRESHOLD
MB_CIRCUIT_OPEN_SECONDS = providers.MB_CIRCUIT_OPEN_SECONDS
MB_CIRCUIT_OPEN_SECONDS_429 = providers.MB_CIRCUIT_OPEN_SECONDS_429
MB_MIN_REQUEST_INTERVAL = providers.MB_MIN_REQUEST_INTERVAL
MB_USER_AGENT = providers.MB_USER_AGENT
MB_USER_AGENT_CONTACT = providers.MB_USER_AGENT_CONTACT
MB_INFO_CACHE_TTL_DAYS = providers.MB_INFO_CACHE_TTL_DAYS
MB_DAILY_DOWNLOAD_LIMIT = providers.MB_DAILY_DOWNLOAD_LIMIT
MB_MAX_INFO_CALLS_PER_RUN = providers.MB_MAX_INFO_CALLS_PER_RUN
MB_USE_GET_FILE_TYPE_QUERY = providers.MB_USE_GET_FILE_TYPE_QUERY
MB_GET_FILE_TYPE_TIMEOUT = providers.MB_GET_FILE_TYPE_TIMEOUT
MB_SIGINFO_QUERIES = providers.MB_SIGINFO_QUERIES
MB_TAGINFO_QUERIES = providers.MB_TAGINFO_QUERIES
MB_SIGINFO_PER_QUERY = providers.MB_SIGINFO_PER_QUERY
THREATFOX_API_URL = providers.THREATFOX_API_URL
TF_MIN_REQUEST_INTERVAL = providers.TF_MIN_REQUEST_INTERVAL
TF_GET_IOCS_TIMEOUT = providers.TF_GET_IOCS_TIMEOUT
TF_GET_IOCS_DAYS_DEFAULT = providers.TF_GET_IOCS_DAYS_DEFAULT
TF_CIRCUIT_FAILURE_THRESHOLD = providers.TF_CIRCUIT_FAILURE_THRESHOLD
TF_CIRCUIT_OPEN_SECONDS = providers.TF_CIRCUIT_OPEN_SECONDS
TF_CIRCUIT_OPEN_SECONDS_429 = providers.TF_CIRCUIT_OPEN_SECONDS_429
TF_USER_AGENT = providers.TF_USER_AGENT
THREATFOX_DISCOVERY_SCAN_MULT = providers.THREATFOX_DISCOVERY_SCAN_MULT
THREATFOX_TAG_QUERIES = providers.THREATFOX_TAG_QUERIES
THREATFOX_TAGINFO_LIMIT = providers.THREATFOX_TAGINFO_LIMIT
CTI_HOST_BLOCK_SECONDS_403 = providers.CTI_HOST_BLOCK_SECONDS_403
CTI_HOST_BLOCK_SECONDS_429 = providers.CTI_HOST_BLOCK_SECONDS_429
CTI_HOST_BLOCK_SECONDS_TRANSPORT = providers.CTI_HOST_BLOCK_SECONDS_TRANSPORT
CTI_PAGE_MAX_BYTES = providers.CTI_PAGE_MAX_BYTES
CTI_REQUEST_TIMEOUT = providers.CTI_REQUEST_TIMEOUT
OTX_ENABLED = providers.OTX_ENABLED
OTX_PULSE_DAYS = providers.OTX_PULSE_DAYS
OTX_PULSE_LIMIT = providers.OTX_PULSE_LIMIT
OTX_PULSE_MAX_HASHES = providers.OTX_PULSE_MAX_HASHES
OTX_SKIP_SEMANTIC_FILTER_BOOTSTRAP = providers.OTX_SKIP_SEMANTIC_FILTER_BOOTSTRAP
OLLAMA_TIMEOUT = providers.OLLAMA_TIMEOUT
GITHUB_API_URL = providers.GITHUB_API_URL

# --- Static source inventories (re-exported from collection/inventory.py) ---
# GITHUB_BENIGN_REPOS, SYSINTERNALS_BASE_URLS, CTI_DOWNLOAD_ALLOWLIST imported at top

# --- Feature schema (re-exported from ml/feature_schema.py) ---
# EXEC_API_NAMES, FEATURE_NAMES imported at top

__all__ = [
    "PROJECT_ROOT",
    "SANDBOX_DIR",
    "DB_PATH",
    "BENIGN_DIR",
    "MODEL_PATH",
    "ADWIN_PATH",
    "EVAL_LOG_PATH",
    "EVAL_STATE_PATH",
    "DRIFT_LOG_PATH",
    "MODEL_UPDATE_LOG_PATH",
    "TRAINING_HISTORY_PATH",
    "LOG_PATH",
    "FIGURES_DIR",
    "REPOS_DIR",
    "ensure_dirs",
    "OTX_API_KEY",
    "OLLAMA_BASE_URL",
    "OLLAMA_MODEL",
    "get_auth_key",
    "get_github_token",
    "get_malshare_api_key",
    "get_secrets",
    "allow_local_benign",
    "malshare_enabled",
    "otx_enabled",
    "mb_fallback_malshare",
    "pe_source_discovery_enabled",
    "ollama_source_selection_enabled",
    "ollama_drift_context_report_enabled",
    "SCHED_ENABLED",
    "SCHED_INTERVAL_SECONDS",
    "SCHED_MAX_RUNS",
    "SCHED_RUN_ON_START",
    "SCHED_JITTER_SECONDS",
    "SCHED_ERROR_BACKOFF_SECONDS",
    "SCHED_MAX_BACKOFF_SECONDS",
    "BOOTSTRAP_MAX_RUNS",
    "BOOTSTRAP_INTERVAL_SECONDS",
    "VERBOSE",
    "LOG_MAX_BYTES",
    "LOG_BACKUP_COUNT",
    "OLLAMA_LOG_DETAIL",
    "OLLAMA_LOG_MAX_CHARS",
    "OLLAMA_LOG_CONSOLE_PREVIEW",
    "ALLOW_LOCAL_BENIGN",
    "MALSHARE_ENABLED",
    "MB_FALLBACK_MALSHARE",
    "PE_SOURCE_DISCOVERY_ENABLED",
    "CTI_SEED_SOURCES_ENABLED",
    "OLLAMA_ENABLED",
    "OLLAMA_SOURCE_SELECTION_ENABLED",
    "OLLAMA_DRIFT_CONTEXT_REPORT_ENABLED",
    "FORCED_BENIGN_PROVIDER",
    "REPLAY_BUDGET",
    "MIN_TRAIN_MALWARE",
    "MIN_TRAIN_BENIGN",
    "PE_FETCH_LIMIT",
    "THRESHOLD_RETRAIN_MIN_NEW_SAMPLES",
    "TARGET_FPR",
    "TARGET_FPR_BOOTSTRAP",
    "TARGET_FPR_GROWTH",
    "TARGET_FPR_BENIGN_TIER_BOOTSTRAP",
    "TARGET_FPR_BENIGN_TIER_PRODUCTION",
    "get_dynamic_target_fpr",
    "FEATURE_SELECTION_K",
    "OPTUNA_TRIALS",
    "OPTUNA_TIMEOUT",
    "REPLAY_FRACTION",
    "ADWIN_DELTA",
    "DRIFT_WINDOW_DAYS",
    "DRIFT_MIN_WINDOW_SAMPLES",
    "DRIFT_MEAN_SHIFT_THRESHOLD",
    "DRIFT_CORR_SHIFT_THRESHOLD",
    "MADAR_CONTAMINATION",
    "MADAR_ANOMALOUS_RATIO",
    "MADAR_CLASS_RATIO",
    "MADAR_BUDGET_STRATEGY",
    "CONTINUATION_TREES",
    "MAX_TOTAL_TREES",
    "MODEL_ARCHIVE_DEPTH",
    "FEATURE_SET_VERSION",
    "FEATURE_DIM",
    "SEMANTIC_MIN_CONFIDENCE",
    "SEMANTIC_REQUIRE_TECHNICAL_REPORT",
    "EVAL_EVERY_RUNS",
    "EVAL_SKIP_BOOTSTRAP",
    "TESSERACT_MIXED_UNTIL_HEALTHY",
    "MIN_BENIGN_FOR_FPR",
    "TARGET_MALWARE_BENIGN_RATIO",
    "BENIGN_PROVIDER_NAMES",
    "IMBALANCE_ALERT_RATIO",
    "MALWARE_FALLBACK_PROVIDERS",
    "FALLBACK_PE_CHECK_MULT",
    "PE_DOWNLOAD_MAX_BYTES",
    "BENIGN_NET_REPO_URL",
    "PE_DISCOVERY_MAX_URLS",
    "MIN_PE_SOURCES",
    "INTEL_MIN_POLL_INTERVAL",
    "INTEL_MAX_POLL_INTERVAL",
    "PROVIDER_COOLDOWN_ZERO_RUNS",
    "PROVIDER_COOLDOWN_SECONDS",
    "PROVIDER_COOLDOWN_MIN_ATTEMPTS",
    "STEADY_BENIGN_EVERY_N",
    "API_URL",
    "ZIP_PASSWORD",
    "MB_CIRCUIT_FAILURE_THRESHOLD",
    "MB_CIRCUIT_OPEN_SECONDS",
    "MB_CIRCUIT_OPEN_SECONDS_429",
    "MB_MIN_REQUEST_INTERVAL",
    "MB_USER_AGENT",
    "MB_USER_AGENT_CONTACT",
    "MB_INFO_CACHE_TTL_DAYS",
    "MB_DAILY_DOWNLOAD_LIMIT",
    "MB_MAX_INFO_CALLS_PER_RUN",
    "MB_USE_GET_FILE_TYPE_QUERY",
    "MB_GET_FILE_TYPE_TIMEOUT",
    "MB_SIGINFO_QUERIES",
    "MB_TAGINFO_QUERIES",
    "MB_SIGINFO_PER_QUERY",
    "THREATFOX_API_URL",
    "TF_MIN_REQUEST_INTERVAL",
    "TF_GET_IOCS_TIMEOUT",
    "TF_GET_IOCS_DAYS_DEFAULT",
    "TF_CIRCUIT_FAILURE_THRESHOLD",
    "TF_CIRCUIT_OPEN_SECONDS",
    "TF_CIRCUIT_OPEN_SECONDS_429",
    "TF_USER_AGENT",
    "THREATFOX_DISCOVERY_SCAN_MULT",
    "THREATFOX_TAG_QUERIES",
    "THREATFOX_TAGINFO_LIMIT",
    "CTI_HOST_BLOCK_SECONDS_403",
    "CTI_HOST_BLOCK_SECONDS_429",
    "CTI_HOST_BLOCK_SECONDS_TRANSPORT",
    "CTI_PAGE_MAX_BYTES",
    "CTI_REQUEST_TIMEOUT",
    "CTI_DOWNLOAD_ALLOWLIST",
    "OTX_ENABLED",
    "OTX_PULSE_DAYS",
    "OTX_PULSE_LIMIT",
    "OTX_PULSE_MAX_HASHES",
    "OTX_SKIP_SEMANTIC_FILTER_BOOTSTRAP",
    "OLLAMA_TIMEOUT",
    "REPORT_LANGUAGE",
    "SYSINTERNALS_BASE_URLS",
    "GITHUB_API_URL",
    "GITHUB_BENIGN_REPOS",
    "EXEC_API_NAMES",
    "FEATURE_NAMES",
]
